"""empty message

Revision ID: 68e72cb22ff7
Revises: 
Create Date: 2021-10-06 18:33:50.707106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e72cb22ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('iamarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=True),
    sa.Column('particulars', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('invigillator', sa.String(length=120), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('obtained_marks', sa.Integer(), nullable=True),
    sa.Column('staff_initial', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regnum', sa.String(length=40), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('publisher', sa.String(length=220), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('books_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['books_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    op.create_table('students2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regnum', sa.String(length=20), nullable=True),
    sa.Column('sname', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('father', sa.String(length=120), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('caste', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('iamarks_id', sa.Integer(), nullable=True),
    sa.Column('semister', sa.String(length=150), nullable=True),
    sa.Column('fee_paid', sa.Integer(), nullable=True),
    sa.Column('fee_due', sa.Integer(), nullable=True),
    sa.Column('scholarship', sa.Integer(), nullable=True),
    sa.Column('books_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['books_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['iamarks_id'], ['iamarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regnum')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('iamarks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iamarks_id'], ['iamarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('students2')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_table('libraries')
    op.drop_table('roles')
    op.drop_table('iamarks')
    op.drop_table('branches')
    op.drop_table('books')
    # ### end Alembic commands ###
